# action.yml
name: 'Notebook to Markdown Converted'
description: 'Converts a jupyter notebook to a markdownfile'
inputs:
  nb-filename:  # id of input
    description: 'The notebook filename'
    required: false
    default: 'notebook.ipynb'
  md-filename:  # id of input
    description: 'The output markdown filename'
    required: false
    default: 'README.md'
outputs:
  state: # id of output
    description: 'The final state'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.nb-filename }}
    - ${{ inputs.md-filename }}
